import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub, AiOutlineConsoleSql} from "react-icons/ai";
import { SiJavascript, SiPython, SiTailwindcss, SiJava, SiExpress, SiReact } from 'react-icons/si';
import {DiMongodb} from "react-icons/di"
import Image from "next/image";
import matthew from '../public/matthew-wave.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matthew Slifer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40">
        <section className=" min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl'>Developed by Matthew</h1>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl lg:text-8xl'>Matthew Slifer</h2>
            <h3 className=' text-2xl py-2 md:text-3xl lg:text-4xl'>Full Stack Software Engineer</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-lg lg:text-xl'>Software engineer intern with experience designing, developing, and implementing full-stack applications.</p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://www.linkedin.com/in/matthew-slifer/'><AiFillLinkedin/></a>
            <a href='https://github.com/matthewslifer'><AiFillGithub/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={matthew} layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <div>
            <h3 className=' text-3xl py-1'>About Me</h3>
            <h4 className='text-xl py-1'>Technologies I Use</h4>
            <div className=' text-5xl flex justify-center gap-5 py-3 text-gray-600 text-center shadow-lg p-10 rounded-xl my-10'>
              <SiJavascript/>
              <SiJava />
              <SiPython />
              <SiReact />
              <SiTailwindcss />
              <SiExpress />
              <DiMongodb />
              <AiOutlineConsoleSql />
            </div>
            <h4 className='text-xl py-1'>Profesional Experience</h4>
            <div className=' text-md py-2 leading-8 text-gray-800 text-center shadow-lg p-10 rounded-xl my-10'>
              <h5 className=' text-lg font-bold'>Software Engineer Intern - Arlite - November 2022 to Current</h5>
              <p>In this role, I successfully developed and implemented a full-stack employee portal application using React.JS, Node.JS, JavaScript, and Express, including front-end design and user authentication using Axios and JSON web tokens. </p>
              <h5 className=' text-lg font-bold'>Research Analyst - UC Davis College of Agricultural and Environmental Sciences - September 2021 to June 2022</h5>
              <p>Conducted research on the social and economic impact of hydraulic fracking, including database queries using SQL and performing quantitative descriptive statistical analysis on data. Compiled statistical findings and insights into reports for presentation to the research team.</p>
            </div>
            <h4 className='text-xl py-1'>Education</h4>
            <div className=' text-md py-2 leading-8 text-gray-800 text-center shadow-lg p-10 rounded-xl my-10'>
              I have a Bachelors of Science of the University of California, Davis in Environmental Science and Management.
              I was introduced to computer programming within the coursework of my major and found that I wanted to pursue this field as a full-time career.
              After graduation, I enrolled in a coding bootcamp, App Academy, where I completed courses in JS, OOP, HTML, CSS, SQL, Databases, Data Structures, Python, Web Security, and more.
              Since, I have completed my certification in Google Data Analytics and continue to work on personal projects to refine and develop programming skills.
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className=' text-3xl py-1'>Portfolio</h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="basis-1/3 flex-1"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
              <h3 className=' text-cyan-700'><a href="https://github.com/matthewslifer/Matthew_Slifer_Profile_Website">Portfolio Website</a></h3>
              <p className=' text-sm'>Next.JS, Tailwinds</p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
              <h3 className=' text-cyan-700'><a href="https://github.com/matthewslifer/React-Weather-App">React Weather Application</a></h3>
              <p className=' text-sm'>
                React.JS, CSS, OpenWeatherMap API
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
              <h3 className=' text-cyan-700'><a href="https://github.com/matthewslifer/E-Commerce-Website">E-Commerce Website</a></h3>
              <p className=' text-sm'>
                Next.JS, Sanity.IO, JavaScript, CRUD Operations on backend database, CSS
              </p>
            </div>
          </div>
          </div>
        </section>
      </main>
    </div>
  )
}
